drm/msm: Fix implicit function declaration of dsi_display HBM functions
In drm_sysfs.c, functions dsi_display_get_hbm_status and dsi_display_set_hbm
were called without any forward declaration or header inclusion, causing compilation errors:
error: implicit declaration of function 'dsi_display_get_hbm_status' [-Werror,-Wimplicit-function-declaration]
error: implicit declaration of function 'dsi_display_set_hbm' [-Werror,-Wimplicit-function-declaration]

Fix this by declaring the prototypes of these functions, and wrap the corresponding
callback functions inside the CONFIG_WT_QGKI macro to match the device attribute definition.

Signed-off-by: Mr. Amrita Das <bhabanidas431@gmail.com>